# Site metadata
keywords: Network analysis, Supply chain management
description: Academic Website of Iryna Malacina
title: Homepage of Iryna Malacina

author: Iryna Malacina
authorimg: images/myphoto2.jpg
authoroccup: Researcher

uni: LUT University
uniurl: http://www.lut.fi

vcard: 'mailto:iryna.maliatsina@lut.fi'
#office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
twitter: IrynaMalacina
#keybase: dderler
linkedin: malacina
#dblp: hd/d/Derler:David
scholar: -RxwRJcAAAAJ&hl

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
    - keybase.txt
include:

