# Site metadata
keywords: Network analysis, Supply chain management
description: Academic Website of Iryna Malacina
title: Homepage of Iryna Malacina

author: Iryna Malacina
authorimg: images/myphoto2.jpg
authoroccup: researcher

#inst: DFINITY
#insturl: https://www.dfinity.org
uni: Graz University of Technology
uniurl: http://www.tugraz.at

vcard: 'mailto:david@dfinity.org'
office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
twitter: dderler
keybase: dderler
linkedin: david-derler-08630495
dblp: hd/d/Derler:David
scholar: YfMKI0wAAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - keybase.txt
